# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.5.0
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Run build
          command: yarn build

  test:
    docker:
      - image: circleci/node:9.5.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run testing suite
          command: yarn test --runInBand --ci --coverage

      - run:
        name: Send coverage to CodeCov
        command: bash <(curl -s https://codecov.io/bash)
    
  deploy-master: 
    docker:
      - image: circleci/node:9.5.0

    working_directory: ~/repo
    
    steps: 
      - checkout

      - run: 
          name: Deploy to Now
          command: npx now --token ${NOW_TOKEN} --team 'chingu-bears-18' --public

      - run: 
          name: Set new deployment alias
          command: npx now --token ${NOW_TOKEN} --team 'chingu-bears-18' alias 'bears-18'

      - run:
          name: Cleanup older instance
          command: npx now-purge --token ${NOW_TOKEN} --team 'chingu-bears-18'

  deploy-dev:    
    docker:
      - image: circleci/node:9.5.0

    working_directory: ~/repo

    steps: 
      - checkout

      - run: 
          name: Deploy to Now
          command: npx now --token ${NOW_TOKEN} --team 'chingu-bears-18' --public

      - run: 
          name: Set new deployment alias
          command: npx now --token ${NOW_TOKEN} --team 'chingu-bears-18' alias 'bears-18-dev'

      - run:
          name: Cleanup older instance
          command: npx now-purge --token ${NOW_TOKEN} --team 'chingu-bears-18'

workflows:
  version: 2
  build-test-deploy:
      jobs: 
        - build
        - test:
            requires: 
              - build
        - deploy-dev:
            requires: 
              - test
            filters:
              branches:
                only: develop
        - deploy-master:
            requires: 
              - test
            filters:
              branches:
                only: master
  


